config/routes.rb
Rails.application.routes.draw do
  get 'sessions/create'

  get 'sessions/destroy'

  get 'home/show'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    get 'pages/index'

    get 'pages/about'

    get 'pages/contact'

  #devise_for :users
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root "home#index"
    get '/about', to: 'pages#about'
    get '/contact', to: 'pages#contact'
    resources :pageants do
      resources :contestants
    end
    resources :contestants
    resources :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contestant.rb
class Contestant < ApplicationRecord
    mount_uploader :image, ImageUploader
    validates_presence_of :image
    validates :con_num, presence: true
    validates :name, presence: true, length: { minimum: 5, maximum: 20 }
    validates :profile, presence: true, length: { minimum: 5, maximum: 40 }
    
    belongs_to :pageant, optional: true
    #belongs_to :user
end

app/models/pageant.rb
class Pageant < ApplicationRecord
    mount_uploader :image, ImageUploader
    validates :name, presence: true, length: { minimum: 5, maximum: 30 }
    validates :description, presence: true, length: { minimum: 10, maximum: 150 }
    validates :category, presence: true, length: { minimum: 5, maximum: 20 }
    
    #validates_inclusion_of :time_zone, in: ActiveSupport::TimeZone.all(&:to_s)
    
    
    default_scope -> {order(updated_at: :desc)}
    belongs_to :user, optional: true
    has_many :contestants, dependent: :destroy
    accepts_nested_attributes_for :contestants
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
         has_many :pageants  
         has_many :contestants, through: :pageants
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
 
end

app/controllers/contestants_controller.rb
class ContestantsController < ApplicationController
    
         before_action :set_contestant, only: [:show, :edit, :update, :delete]
    
    def index
        @contestants = Contestant.all
    end
    
    def new
        @contestant = Contestant.new
    end
    
    def create
        
          #@pageant = Pageant.find(params[:pageant_id])
            #@contestant = @pageant.contestants.create(contestant_params)
            #redirect_to pageant_path(@pageant)

        
            @contestant = Contestant.new(contestant_params)
                if @contestant.save
                session[:user_id] = @user_id
                flash[:success] = "Contestant created"
                redirect_to contestant_path(@contestant)   
                    else
                        render 'new'
                   end
                end
    
    def show
        #@chef_recipes = @chef.recipes.paginate(page: params[:page], per_page: 3)
    end
    
    def edit
        
    end
    
    def update
        if @contestant.update(contestant_params)
            flash[:success] = "Contestant was created successfully"
            redirect_to @contestant
        else
            render 'edit'
        end
    end
    
    def destroy
        #@contestant.destroy
        #flash[:danger] = "contestant has been deleted"
        #redirect_to contestants_path
        
            @pageant = Pageant.find(params[:pageant_id])
            @contestant = @pageant.contestants.find(params[:id])
            @contestant.destroy
            flash[:danger] = "contestant has been deleted"
            redirect_to pageant_path(@pageant)
        
        
    end
    
    private
    
        def contestant_params
            params.require(:contestant).permit(:con_num, :name, :profile, :image, :pageant_id)
        end
        
    
        def set_contestant
            @contestant = Contestant.find(params[:id])
        end
    
        def require_same_user
            if current_user != @user
                flash[:danger] = "You can only delete your own account"
                redirect_to root_path
            end
        end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
  end
  
  def show
  end
end

app/controllers/pageants_controller.rb
class PageantsController < ApplicationController
  before_action :set_pageant, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  # GET /pageants
  # GET /pageants.json
  def index
    @pageants = Pageant.all
  end

  # GET /pageants/new
  def new
   # @pageant = current_user.pageant.build 
   @pageant = Pageant.new
  end
  
  def create
    #@pageant = Pageant.new(pageant_params)
      @pageant = current_user.pageants.new(pageant_params)
      #git @pageant.user_id = current_user
      if @pageant.save
        flash[:success] = "Pageant was created successfully"
        redirect_to pageant_path(@pageant)
      else
        render 'new'
      end
    end
  # GET /pageants/1
  # GET /pageants/1.json
  def show
  end

  # GET /pageants/1/edit
  def edit
  end

  
  # PATCH/PUT /pageants/1
  # PATCH/PUT /pageants/1.json
  def update
    respond_to do |format|
      if @pageant.update(pageant_params)
        format.html { redirect_to @pageant, notice: 'Pageant was successfully updated.' }
        format.json { render :show, status: :ok, location: @pageant }
      else
        format.html { render :edit }
        format.json { render json: @pageant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pageants/1
  # DELETE /pageants/1.json
  def destroy
    @pageant.destroy
        flash[:danger] = "Pageant and all associated contestants have been deleted"
        redirect_to pageants_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pageant
      @pageant = Pageant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pageant_params
      #params.fetch(:pageant, {})
        params.require(:pageant).permit(:name, :description, :category, :timezone, :image, :startdate, :enddate, :user_id)
      end
      def require_same_user
        if current_user != @user
          flash[:danger] = "You can only edit or delete your own account"
          redirect_to pageants_path
        end
      end
    end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  
  def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
        session[:user_id] = user.id
        flash[:success] = "You have successfully logged in"
        redirect_to user
    else
        flash.now[:danger] = "Wrong login Information"
        render 'new'
        end
    end
    
    def destroy
        session[:user_id] = nil
        flash[:success] = "You have logged out"
        redirect_to root_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contestants_helper.rb
module ContestantsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/contestants/_form.html.erb
<%= render 'shared/errors', obj: @contestant  %>
<div class="login_edit">
<div class="row">
    <div class="col-md-12">
        <%= form_for([@contestant], :html => { class: "form-horizontal", multipart: true, role: "form" }) do |f| %>
    <div class="form-group">
        <div class="control-label col-md-2">
            <%= f.label :Number %>
            </div>
            <div class="col-md-8">
                <%= f.text_field :con_num, class: "form-control", placeholder: "Contestant's Number", autofocus: true %>
            </div>
            </div>
        <div class="form-group">
        <div class="control-label col-md-2">
            <%= f.label :Name %>
            </div>
            <div class="col-md-8">
                <%= f.text_field :name, class: "form-control", placeholder: "Contestant's Name" %>
            </div>
            </div>
            <div class="form-group">
        <div class="control-label col-md-2">
            <%= f.label :Profile %>
            </div>
            <div class="col-md-8">
                <%= f.text_area :profile, rows:5, class: "form-control", placeholder: "Contestant's Profile" %>
            </div>
            </div>
            
            <div class="form-group">
              <div class="control-label col-md-2">
                <%= f.label :image, "Image" %>
              </div>
              <div class="col-md-8">
                <%= f.file_field :image, accept: 'image/jpeg,image/gif,image/png', class: "btn btn-primary btn-sm" %>
              </div>
                </div>
            
        <div form-group>
          <div class="col-md-offset-2 col-md-10">
              <%=  f.submit class: "btn btn-primary btn-md" %>
          </div>  
        </div>
        <% end %>
        <div class="col-md-4 col-md-offset-4 colormatch">
            [<%= link_to "Pageants listing", pageants_path %>]
        </div>
</div>
</div></div>

app/views/contestants/new.html.erb
<%= render 'form' %>

app/views/home/index.html.erb
 <div class="jumbotron center">
       <h1 align="center">welcome to ezyvote</h1>  
      <!-- <h2 align="center">The best Pageant Voting app</h2>-->
       <p><%= link_to "login with facebook", "#", class: "btn btn-danger 
       btn-lg btn-xlarge center" %></p>
    </div>
    
      </div>
      <div class="row">
      <div class="col-xs-12 col-sm-4">Pageant information goes here as a link after they are created</div>
      <div class="col-xs-12 col-sm-4">Pageant information goes here as a link after they are created</div>
      <!-- Optional: clear the XS cols if their content doesn't match in height-->
  <div class="clearfix visible-xs-block"></div>
  <div class="col-xs-12 col-sm-4">Pageant information goes here as a link after they are created</div>
  </div>

app/views/home/show.html.erb
<h1>Home#show</h1>
<p>Find me in app/views/home/show.html.erb</p>

app/views/layouts/_footer.html.erb
<div id="footer">
      <!--	<div class="row">
          <ul class="list-unstyled">
            <li class="col-md-3 col-sm-4 col-xs-6">
              <a href="index.html">Home</a>
            </li>
            <li class="col-md-3 col-sm-4 col-xs-6">
              <a href="services.html">Services</a>
            </li>
            <li class="col-md-3 col-sm-4 col-xs-6">
              <a href="404.html">Studies</a>
            </li>
          </ul>
		</div><!--/row-->
</div>

app/views/layouts/_messages.html.erb
<dic class="row">
<div class="col-md-10 col-md-offset-1">
    <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name %>">
    <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= msg %>
    </div>
        <% end %>
    </div>
</div>

app/views/layouts/_nav.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    
   
<!-- Fixed navbar 

    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>-->

<nav class="navbar navbar-default navbar-fixed-top" >
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "ezyvote", root_path, class: "navbar-brand", id: "logo" %>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path, class: "links" %></li>
            <li><%= link_to "Pageants", pageants_path, class: "links" %></li>
            <li><%= link_to "Create Vote", new_pageant_path, class: "links" %></li>
            
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <!-- devise data  -->
          <% if user_signed_in? %>
          
          <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'links' %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'links' %></li>
          
            <% else %>
          <li><%= link_to "Sign up", new_user_registration_path, :class => 'links' %></li>
          <li><%= link_to "Login", new_user_session_path, :class => 'links' %></li>
          
          <% end %>

        
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ezyvote</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    
      <%= render 'layouts/nav' %>
      
      <div class="container">
 
    <%= yield %>
    </div>
    <!--Here was footer, now he is gone-->
    <div>
    <%= render "layouts/footer" %>
    </div>
  </body>
</html>

app/views/pageants/_form.html.erb
<%= render 'shared/errors', obj: @pageant  %>

<div class="login_create">
<div class="row">
    <div class="col-md-12">
        <%= form_for(@pageant, :html => { class: "form-horizontal", multipart: true, role: "form" }) do |f| %>
    <div class="form-group">
        <div class="control-label col-md-2">
            <%= f.label :name %>
            </div>
            <div class="col-md-8">
                <%= f.text_field :name, class: "form-control", placeholder: "Name of Pageant", autofocus: true %>
            </div>
            </div>
        <div class="form-group">
        <div class="control-label col-md-2">
            <%= f.label :description %>
            </div>
            <div class="col-md-8">
                <%= f.text_area :description, rows:3, class: "form-control", placeholder: "Description of Pageant" %>
            </div>
            </div>
            <div class="form-group">
                <div class="control-label col-md-2">
                    <%= f.label :category %>
                </div>
                <div class="col-md-8">
                    <%= f.text_field :category, class: "form-control", placeholder: "Give a category of your choice" %>
                </div>
            </div>
            
            <div class="form-group">
                <div class="control-label col-md-2">
                    <%= f.label :StartDate, "Start Date" %>
                </div>
                <div class="col-md-8">
                    <%= f.date_field :startdate, class: "form-control", placeholder: "Enter the start date" %>
                </div>
            </div>
            
            <div class="form-group">
                <div class="control-label col-md-2">
                    <%= f.label :Enddate, "End Date" %>
                </div>
                <div class="col-md-8">
                    <%= f.date_field :enddate, class: "form-control", placeholder: "Enter the end date" %>
                </div>
            </div>
            
            <div class="form-group">
                <div class="control-label col-md-2">
                    <%= f.label :timezone %>
                </div>
                <div class="col-md-8">
                    <%= f.time_zone_select :timezone, nil, {}, class: 'form-control' %>
                </div>
            </div>
            
            <div class="form-group">
                <div class="control-label col-md-2">
                    <%= f.label :image, "Add Banner" %>
                </div>
                <div class="col-md-8">
                    <%= f.file_field :image, accept: 'image/jpeg,image/gif,image/png', class: "btn btn-primary btn-sm" %>
                </div>
            </div>
              <%= f.hidden_field :user_id, value: current_user.id %>
            <div form-group>
                <div class="col-md-offset-2 col-md-10">
                      <%=  f.submit class: "btn btn-primary btn-md" %>
                </div>  
            </div>
                        <% end %>
            <div class="col-md-4 col-md-offset-4 colormatch">
                    [<%= link_to "Pageants listing", pageants_path %>]
            </div>
</div>
</div>
</div>

app/views/pageants/edit.html.erb
<h1 align="center">Editing Pageant</h1><hr/>

<%= render 'form', pageant: @pageant %>

app/views/pageants/index.html.erb
<!--<p id="notice"></p>-->
<h2 align="center">Pageants</h2><hr/>

<% @pageants.each do |pageant| %>
      <div class="col-sm-6 col-md-3">
        <div class="=thumbnail thumb-box">
          <h3 class="triad"><%= link_to pageant.name, pageant_path(pageant) %></h3>
          <%= image_tag( pageant.image, size: "180x180" ) %>
        </div>
      </div>
      <% end %>
    

app/views/pageants/new.html.erb
<h3 class="col-md-8" align="center">Create Vote</h3>
<div class="col-md-8">
<%= render 'form', pageant: @pageant %>
</div>



<!--Side content-->
<div class="well well-lg login_new col-md-4">
    SMS Votes
</div>

app/views/pageants/show.html.erb
<div align="center">
    
      </div>
    
    <div>

    <div class="row">
				<div class="col-md-8" >
				    
				<div class="image">
         <%= image_tag @pageant.image.url, class: "img-responsive center-block" if @pageant.image? %>
        </div>
  </br></br>
  <div align="center">
    <ul class="list-inline" id="links">
      
      <li><%= link_to "Add Contestant", new_contestant_path %></li>
      <li><%= link_to "Edit Vote", edit_pageant_path %></li>
      <!--<li><a href="#">Delete</a></li>-->
      <li><%= link_to "Delete", @pageant, method: :delete,
       data: { confirm: "Are you sure you want to delete this pageant?"} %></li>
      <!--<li><a href="#">Something...</a></li>-->
    </ul>
  </div>
  <!--Panel starts from here-->
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 align="center" class="panel-title"><b>Vote Created</b></h4>
  </div>
  <div class="panel-body">
          <h4 align="center"><%= @pageant.name %></h4>
          <h4 align="center"><%= @pageant.description  %></h4>
          <h4 align="center"><%= @pageant.category  %></h4>
          <h4 align="center"><b>Starting:</b> <%= @pageant.startdate.to_s %></h4>
          <h4 align="center"><b>Ending:</b> <%= @pageant.enddate.to_s %></h4>
          <h4 align="center"><b>Time Zone:</b> <%= @pageant.timezone  %></h4>
		</div>
  </div>
</div>
  <!--Ending the panel view here-->

        <div class="panel-heading center">Current Pageants</div>
        <div class="col-md-4">
          <!--Current created pageants appear here-->
        </div>
        </div>
      </div>
       
					
      
 |
<%= link_to 'Back', pageants_path %>
<% render "layouts/footer"%>
</body>
</html>

app/views/pages/contact.html.erb
<h3>Contact Page</h3>

app/views/pages/index.html.erb
<h3>Index Page</h3>

app/views/shared/_errors.html.erb
 <% if obj.errors.any? %>
 <div class="row">
     <div class="col-md-8 col-md-offset-2">
         <div class="panel panel-danger">
             <div class="panel-heading">
             <h2 class="panel-title">
                 <%= pluralize(obj.errors.count, "error") %>
                 prohibited this <%= obj.class %> from being saved:
             </h2>
             <div class="panel-body">
                 <ul>
                     <% obj.errors.full_messages.each do |msg| %>
                 <li><%= msg %></li>
                     <% end %>
                 </ul>
             </div>
             </div>
         </div>
     </div>
 </div>
 <% end %>